"""Initial schema: users, decks, simulation_configs, simulations

Revision ID: 2f8d602d88f9
Revises: 
Create Date: 2025-10-26 14:23:55.625384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f8d602d88f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.Enum('EMAIL', 'GOOGLE', name='authprovider'), nullable=False),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('card_count', sa.String(length=10), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_user_id'), 'decks', ['user_id'], unique=False)
    op.create_table('simulation_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_runs', sa.Integer(), nullable=False),
    sa.Column('default_turns', sa.Integer(), nullable=False),
    sa.Column('key_card_turn_limit', sa.Integer(), nullable=False),
    sa.Column('key_cards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mulligan_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ideal_setups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sideboard_plans', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_configs_user_id'), 'simulation_configs', ['user_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=True),
    sa.Column('config_id', sa.UUID(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('sideboard_plan', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='simulationstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['simulation_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_deck_id'), 'simulations', ['deck_id'], unique=False)
    op.create_index(op.f('ix_simulations_status'), 'simulations', ['status'], unique=False)
    op.create_index(op.f('ix_simulations_user_id'), 'simulations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_user_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_status'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_deck_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_simulation_configs_user_id'), table_name='simulation_configs')
    op.drop_table('simulation_configs')
    op.drop_index(op.f('ix_decks_user_id'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

